requires 'perl', '5.026';
requires 'DBI';
requires 'DBD::Pg';
requires 'Test2::V0';
requires 'MetaCPAN::Client';
requires 'URI';
requires 'LWP::UserAgent';
requires 'LWP::Protocol::https';
requires 'Cpanel::JSON::XS';
requires 'HTML::HTML5::Entities';
requires 'YAML';
requires 'Moo';
